### ISSUE TITLE
fix: plugin template generation

### ISSUE THREAD

**Issue by Ascenio** [VeryGoodOpenSource/very_good_cli#180]
**Description**
Plugin template is crashing and generates Android plugin with embedding < 2.0.

```sh
ascenio@arch> very_good create my_plugin -t flutter_plugin
Can't load Kernel binary: Invalid kernel binary format version.
Unhandled exception:
ProcessException: Standard out
Waiting for another flutter command to release the startup lock...
Running "flutter pub get" in my_plugin_android...                2.700ms
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Standard error
The plugin `my_plugin_android` doesn't have a main class defined in /tmp/tmp.bkOZZqLVdS/my_plugin/my_plugin_android/android/src/main/java/com/example/verygoodcore/my_plugin/MyPluginAndroidPlatform.java or /tmp/tmp.bkOZZqLVdS/my_plugin/my_plugin_android/android/src/main/kotlin/com/example/verygoodcore/my_plugin/MyPluginAndroidPlatform.kt. This is likely to due to an incorrect `androidPackage: com.example.verygoodcore.my_plugin` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.
  Command: flutter packages get
#0      _Cmd._throwIfProcessFailed (package:very_good_cli/src/flutter_cli.dart:119:7)
#1      _Cmd.run (package:very_good_cli/src/flutter_cli.dart:98:7)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#3      Flutter._installPackages (package:very_good_cli/src/flutter_cli.dart:73:5)
<asynchronous suspension>
#4      Flutter.packagesGet (package:very_good_cli/src/flutter_cli.dart:15:5)
<asynchronous suspension>
#5      FlutterPluginTemplate.onGenerateComplete (package:very_good_cli/src/templates/template.dart:117:7)
<asynchronous suspension>
#6      CreateCommand.run (package:very_good_cli/src/commands/create.dart:119:5)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:69:14)
<asynchronous suspension>
#9      main (file:///home/ascenio/.pub-cache/hosted/pub.dartlang.org/very_good_cli-0.4.2/bin/very_good.dart:5:24)
<asynchronous suspension>
```

**Steps To Reproduce**

1. Generate a plugin with `very_good create my_plugin -t flutter_plugin`

**Expected Behavior**
The cli should generate a plugin compatible with Android embedding 2.0 and without crashing.

**Additional Context**
I'm using the cli from a temporary folder, that's why you see `/tmp/tmp.bkOZZqLVdS/` in the logs. No need to be scared about that xD.

**Comment by marcossevilla** [comment]
hi @Ascenio! can you specify the Flutter version you're using by running flutter doctor and sending the output?

**Comment by Ascenio** [comment]
Sure. Here it is:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale pt_BR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by Ascenio** [comment]
I've just upgraded to 2.5.0 and looks like it solves the problem. That's an easy fix :laughing:
