### ISSUE TITLE
fix: plugin template generation

### ISSUE THREAD

**Issue by viviethoang99** [VeryGoodOpenSource/very_good_cli#402]
**Description**
An error occurred while generation the project.

**Steps To Reproduce**
1, Generate a plugin with ```very_good create my_app --desc "My new Flutter app"```
2, Crash generation.
```
✓ Generated 239 file(s) (0.5s)
⠴ Running "flutter packages get" in my_app...Unhandled exception:
ProcessException: Standard out
Running "flutter pub get" in my_app...
Standard error
The current Dart SDK version is 2.17.0-266.8.beta.

Because my_app requires SDK version >=2.17.0 <3.0.0, version solving failed.
pub get failed (1; Because my_app requires SDK version >=2.17.0 <3.0.0, version solving failed.)
  Command: flutter packages get
#0      _Cmd._throwIfProcessFailed (package:very_good_cli/src/cli/cli.dart:62:7)
#1      _Cmd.run (package:very_good_cli/src/cli/cli.dart:33:7)
<asynchronous suspension>
#2      Flutter.packagesGet.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:84:11)
<asynchronous suspension>
#3      _runCommand (package:very_good_cli/src/cli/flutter_cli.dart:249:13)
<asynchronous suspension>
#4      Flutter.packagesGet (package:very_good_cli/src/cli/flutter_cli.dart:70:5)
<asynchronous suspension>
#5      installFlutterPackages (package:very_good_cli/src/commands/create/templates/post_generate_actions.dart:31:5)
<asynchronous suspension>
#6      VeryGoodCoreTemplate.onGenerateComplete (package:very_good_cli/src/commands/create/templates/very_good_core/very_good_core_template.dart:19:5)
<asynchronous suspension>
#7      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:163:5)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:109:18)
<asynchronous suspension>
#10     VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:80:14)
<asynchronous suspension>
#11     main (file:///Users/vihoang/.pub-cache/hosted/pub.dartlang.org/very_good_cli-0.7.2/bin/very_good.dart:5:24)
<asynchronous suspension>
```

**Expected Behavior**
A will create an app that won't crash

**Additional Context**
This is my version of Flutter:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.13.0-0.4.pre, on macOS 11.6 20G165 darwin-x64,
    locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
Dart version:
```
Dart 2.17.0 (build 2.17.0-266.8.beta)
```

**Comment by viviethoang99** [comment]
After I reverted flutter to the ```master branch``` and ```upgraded``` to the latest version, the error was gone.
