### ISSUE TITLE
fix: Invalid version constraint: Expected version number after ">=" in ">=2.12-0-0 <3.0.0", got "2.12-0-0 <3.0.0".)

### ISSUE THREAD

**Issue by draskosaric** [VeryGoodOpenSource/very_good_cli#427]
**Description**
I wanted to create a Flutter project and received pub get error 65. 

**Steps To Reproduce**

1. Enter into terminal `very_good create flutter_todos`
2. Receive the following error:
```
✓ Generated 239 file(s) (0.5s)
⠏ Running "flutter packages get" in flutter_todos...Unhandled exception:
ProcessException: Standard out
Running "flutter pub get" in flutter_todos...
Standard error
Error on line 1, column 1 of ../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/.cache/mocktail-versions.json: Invalid version constraint: Expected version number after ">=" in ">=2.12-0-0 <3.0.0", got "2.12-0-0 <3.0.0".
pub get failed (65; Error on line 1, column 1 of ../../flutter/flutter/.pub-cache/hosted/pub.dartlang.org/.cache/mocktail-versions.json: Invalid version constraint: Expected version number after ">=" in ">=2.12-0-0 <3.0.0", got "2.12-0-0 <3.0.0".)
  Command: flutter packages get
#0      _Cmd._throwIfProcessFailed (package:very_good_cli/src/cli/cli.dart:63:7)
#1      _Cmd.run (package:very_good_cli/src/cli/cli.dart:34:7)
<asynchronous suspension>
#2      Flutter.packagesGet.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:84:11)
<asynchronous suspension>
#3      _runCommand (package:very_good_cli/src/cli/flutter_cli.dart:256:13)
<asynchronous suspension>
#4      Flutter.packagesGet (package:very_good_cli/src/cli/flutter_cli.dart:70:5)
<asynchronous suspension>
#5      installFlutterPackages (package:very_good_cli/src/commands/create/templates/post_generate_actions.dart:31:5)
<asynchronous suspension>
#6      VeryGoodCoreTemplate.onGenerateComplete (package:very_good_cli/src/commands/create/templates/very_good_core/very_good_core_template.dart:19:5)
<asynchronous suspension>
#7      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:163:5)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:109:18)
<asynchronous suspension>
#10     VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:80:14)
<asynchronous suspension>
#11     main (file:///Users/draskosaric/.pub-cache/hosted/pub.dartlang.org/very_good_cli-0.7.6/bin/very_good.dart:5:24)
<asynchronous suspension>
```

**Expected Behavior**
It is expected that project is created and 'pub get' will download the dependencies. Apparently 'pub get' can't be done.

**Screenshots**
None

**Additional Context**

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by draskosaric** [comment]
I updated to v0.7.8. and still receiving the error. I am also using MacOS Monterey, 12.4.

**Comment by felangel** [comment]
Can you try clearing your `.pub-cache` and trying again?

```
# warning this will delete all cached pub packages
rm -rf ../../flutter/flutter/.pub-cache
```

**Comment by draskosaric** [comment]
After deleting global system cache

`flutter pub cache clean`

, I've managed to create a flutter project using very_good. Thanks!
