### ISSUE TITLE
fix: `Unhandled exception` when running `very_good create project_name`

### ISSUE THREAD

**Issue by wujekbogdan** [VeryGoodOpenSource/very_good_cli#459]
**Description**

`Unhandled exception` is thrown when when running `very_good create project_name`

**Steps To Reproduce**

1. Execute `very_good create project_name`
2. An error is thrown:
  ```
    very_good create flutter_test
    ✓ Generated 239 file(s) (1.6s)
    ⠴ Running "flutter packages get" in flutter_test...Unhandled exception:
    ProcessException: Standard out
    Running "flutter pub get" in flutter_test...
    Standard error
    Error on line 21, column 3 of pubspec.yaml: A package may not list itself as a dependency.
       ╷
    21 │   flutter_test:
       │   ^^^^^^^^^^^^
       ╵
    pub get failed (65;    ╵)
      Command: flutter packages get
    #0      _Cmd._throwIfProcessFailed (package:very_good_cli/src/cli/cli.dart:120:7)
    #1      _Cmd.run (package:very_good_cli/src/cli/cli.dart:91:7)
    <asynchronous suspension>
    #2      Flutter.packagesGet.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:96:11)
    <asynchronous suspension>
    #3      _runCommand (package:very_good_cli/src/cli/flutter_cli.dart:271:13)
    <asynchronous suspension>
    #4      Flutter.packagesGet (package:very_good_cli/src/cli/flutter_cli.dart:82:5)
    <asynchronous suspension>
    #5      installFlutterPackages (package:very_good_cli/src/commands/create/templates/post_generate_actions.dart:31:5)
    <asynchronous suspension>
    #6      VeryGoodCoreTemplate.onGenerateComplete (package:very_good_cli/src/commands/create/templates/very_good_core/very_good_core_template.dart:19:5)
    <asynchronous suspension>
    #7      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:174:5)
    <asynchronous suspension>
    #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
    <asynchronous suspension>
    #9      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:110:18)
    <asynchronous suspension>
    #10     VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:81:14)
    <asynchronous suspension>
    #11     main (file:///Users/wb/.pub-cache/hosted/pub.dartlang.org/very_good_cli-0.7.10/bin/very_good.dart:5:24)
    <asynchronous suspension>
  ```

**Expected Behavior**
The process should not fail. A new project should be created.

**Additional Context**

```
flutter --version
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (12 days ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2
```

```
very_good --version
0.7.10
```

**Comment by wujekbogdan** [comment]
I've just realised that the issue was caused by the project name. First, I tried `very_good create flutter` and got this error. Then I tried `very_good create flutter_test` and got the same error, so I assumed that this is a generic issue, but it's not.

The issue is caused by a name conflict `flutter` and `flutter_test` would conflict with Flutter packages dependencies. I realised that while trying to create a project via IDE:

<img width="398" alt="Zrzut ekranu 2022-07-12 o 12 53 40" src="https://user-images.githubusercontent.com/533954/178474384-723644d6-b6c4-4c9d-bb1e-00405ba98c4f.png">

So this isn't really a bug report. It's rather a feature request. The CLI should notify a user when they try to use a restricted project name.

**Comment by renancaraujo** [comment]
Not quite a bug since the project si create, you only cannot do a `pub get` on it because of the name clash. 

We could not spit a huge stack trace went here is an error with `pub get` after creating a project.

**Comment by renancaraujo** [comment]
We could add a warning fro when creating a project with this name.

**Comment by wolfenrain** [comment]
Closing this as it will be hard to figure out what names are allowed and what not without unbundling the mason bricks multiple times.
