### ISSUE TITLE
Unhandled exception: Running "flutter packages get" in test..

### ISSUE THREAD

**Issue by egyleader** [VeryGoodOpenSource/very_good_cli#466]
**Description**

create command fails in running "flutter packages get" command with this error :

```bash
✓ Generated 239 file(s) (1.4s)
⠹ Running "flutter packages get" in test...Unhandled exception:
ProcessException: Standard out
Running "flutter pub get" in test...
Standard error
Because mocktail 0.3.0 depends on test ^1.16.0 and no versions of mocktail match >0.3.0 <0.4.0, mocktail ^0.3.0 requires test ^1.16.0.
So, because test depends on mocktail ^0.3.0 and test is 1.0.0+1, version solving failed.
pub get failed (1; So, because test depends on mocktail ^0.3.0 and test is 1.0.0+1, version solving failed.)
  Command: flutter packages get
#0      _Cmd._throwIfProcessFailed (package:very_good_cli/src/cli/cli.dart:120:7)
#1      _Cmd.run (package:very_good_cli/src/cli/cli.dart:91:7)
<asynchronous suspension>
#2      Flutter.packagesGet.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:96:11)
<asynchronous suspension>
#3      _runCommand (package:very_good_cli/src/cli/flutter_cli.dart:271:13)
<asynchronous suspension>
#4      Flutter.packagesGet (package:very_good_cli/src/cli/flutter_cli.dart:82:5)
<asynchronous suspension>
#5      installFlutterPackages (package:very_good_cli/src/commands/create/templates/post_generate_actions.dart:31:5)
<asynchronous suspension>
#6      VeryGoodCoreTemplate.onGenerateComplete (package:very_good_cli/src/commands/create/templates/very_good_core/very_good_core_template.dart:20:5)
<asynchronous suspension>
#7      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:174:5)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:110:18)
<asynchronous suspension>
#10     VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:81:14)
<asynchronous suspension>
#11     main (file:///C:/Users/egyle/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/very_good_cli-0.7.11/bin/very_good.dart:5:24)
<asynchronous suspension>
```

**Steps To Reproduce**

run command `very_good create test`

**Additional Context**
os : windows 11
ver: 0.7.11

**Comment by Luckey-Elijah** [comment]
Using `test` for a Dart/Flutter project's name is notorious for failing during creating. Try executing with something other than `test`

**Comment by tomarra** [comment]
Looks like this was already answered and has ben open for over a year with no activity. Closing this out as "won't fix"
