### ISSUE TITLE
fix(create-flutter-plugin): directory listing failed

### ISSUE THREAD

**Issue by tomassasovsky** [VeryGoodOpenSource/very_good_cli#610]
**Description**
The command I ran:
`very_good create ncnn --org-name=com.sportsvisio --desc="Native bridge to ncnn, a high-performance neural network inference framework optimized for the mobile platform" --template=flutter_plugin --web=false --linux=false --macos=false --windows=false --publishable`

The output:
```⠏ Bootstrapping... (0.7s)Unhandled exception:
FileSystemException: Directory listing failed, path = 'C:\Users\Tomas\AppData\Local\Mason\Cache\bundled\very_good_flutter_plugin_0.2.1_5b74e6eea4904f8b209d5e5b0789ab77cb28c29b\__brick__\{{project_name.snakeCase()}}\{{#android}}{{project_name.snakeCase()}}_android{{\android}}\android\src\main\kotlin\{{org_name.pathCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      MasonGenerator._fromBrick (package:mason/src/generator.dart:93:14)
#3      MasonGenerator.fromBundle (package:mason/src/generator.dart:72:27)
<asynchronous suspension>
#4      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:165:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:144:18)
<asynchronous suspension>
#7      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:91:14)
<asynchronous suspension>
#8      main (file:///C:/Users/Tomas/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/very_good_cli-0.9.0/bin/very_good.dart:5:24)
<asynchronous suspension>
⠏ Bootstrapping... (0.7s)Unhandled exception:
FileSystemException: Directory listing failed, path = 'C:\Users\Tomas\AppData\Local\Mason\Cache\bundled\very_good_flutter_plugin_0.2.1_5b74e6eea4904f8b209d5e5b0789ab77cb28c29b\__brick__\{{project_name.snakeCase()}}\{{#android}}{{project_name.snakeCase()}}_android{{\android}}\android\src\main\kotlin\{{org_name.pathCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      MasonGenerator._fromBrick (package:mason/src/generator.dart:93:14)
#3      MasonGenerator.fromBundle (package:mason/src/generator.dart:72:27)
<asynchronous suspension>
#4      CreateCommand.run (package:very_good_cli/src/commands/create/create.dart:165:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:144:18)
<asynchronous suspension>
#7      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:91:14)
<asynchronous suspension>
#8      main (file:///C:/Users/Tomas/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/very_good_cli-0.9.0/bin/very_good.dart:5:24)
<asynchronous suspension>
```

Rollback to `v0.8.5` fixes the issue, so it must've been added in `v0.8.6`, as it also breaks there.
It looks like what breaks everything is the update of mason in #579.

**Comment by renancaraujo** [comment]
Tracking this problem on #728

**Comment by renancaraujo** [comment]
We will track this problem on #728 now. Thanks for opening the issue!
