### ISSUE TITLE
fix: `very_good test` failed (with exception)

### ISSUE THREAD

**Issue by eseidel** [VeryGoodOpenSource/very_good_cli#727]
```
eseidel@erics-mbp shorebird % very_good test -r    
...
Running "flutter test" in /Users/eseidel/Documents/GitHub/_shorebird/shorebird/bin/cache/flutter/examples...
✓ Optimizing tests (58ms)
Failed to load "/Users/eseidel/Documents/GitHub/_shorebird/shorebird/bin/cache/flutter/examples/api/test/.test_optimizer.dart": type 'FlutterLocalFileComparator' is not a subtype of type 'LocalFileComparator' in type cast
test/.test_optimizer.dart 371:47  _TestOptimizationAwareGoldenFileComparator._goldenFilePaths
test/.test_optimizer.dart 361:27  new _TestOptimizationAwareGoldenFileComparator
test/.test_optimizer.dart 182:26  main

Unhandled exception:
Null check operator used on a null value
#0      _actualTestPath (package:very_good_cli/src/cli/flutter_cli.dart:502:62)
#1      _flutterTest.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:398:13)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

I'm not sure what "optimizationApplied" means, but it seems to use a value which is not null-checked:
https://github.com/VeryGoodOpenSource/very_good_cli/blob/main/lib/src/cli/flutter_cli.dart#L502

**Comment by eseidel** [comment]
Repro steps:
1. Check out https://github.com/flutter/flutter
2. run `very_good test -r` at the root.

Expected result: Should not crash.

**Comment by eseidel** [comment]
Did not seem to crash when I used `very_good test -j=1 -r` in flutter/flutter.  🤷

**Comment by eseidel** [comment]
Thanks!
