### ISSUE TITLE
fix: Plugin creation throws PathNotFoundException in Windows

### ISSUE THREAD

**Issue by yahu1031** [VeryGoodOpenSource/very_good_cli#728]
**Description**
Creating a flutter plugin throws PathNotFound Exception. These exceptions must be handled by some error statements.

**Steps To Reproduce**

1. Upgraded flutter from 3.7.3 - 3.7.12
2. Install vgv CLI
3. `very_good create flutter_plugin sky_client`

Now you see this error.

```console
PS C:\Users\yaswa\Desktop> very_good create flutter_plugin sky_client
Unhandled exception:
PathNotFoundException: Directory listing failed, path = 'C:\Users\yaswa\AppData\Local\Mason\Cache\bundled\very_good_flutter_plugin_0.3.3_22878f28a4fe654485c306b2b7c238e94c4ec37c\__brick__\{{project_name.snakeCase()}}\{{#android}}{{project_name.snakeCase()}}_android{{\android}}\android\src\main\kotlin\{{org_name.pathCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      MasonGenerator._fromBrick (package:mason/src/generator.dart:91:14)
#3      MasonGenerator.fromBundle (package:mason/src/generator.dart:70:27)
<asynchronous suspension>
#4      CreateSubCommand.run (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:199:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:211:18)
<asynchronous suspension>
#7      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:148:14)
<asynchronous suspension>
#8      main (file:///C:/Users/yaswa/AppData/Local/Pub/Cache/hosted/pub.dev/very_good_cli-0.13.1/bin/very_good.dart:5:24)
<asynchronous suspension>
Unhandled exception:
PathNotFoundException: Directory listing failed, path = 'C:\Users\yaswa\AppData\Local\Mason\Cache\bundled\very_good_flutter_plugin_0.3.3_22878f28a4fe654485c306b2b7c238e94c4ec37c\__brick__\{{project_name.snakeCase()}}\{{#android}}{{project_name.snakeCase()}}_android{{\android}}\android\src\main\kotlin\{{org_name.pathCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      MasonGenerator._fromBrick (package:mason/src/generator.dart:91:14)
#3      MasonGenerator.fromBundle (package:mason/src/generator.dart:70:27)
<asynchronous suspension>
#4      CreateSubCommand.run (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:199:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:211:18)
<asynchronous suspension>
#7      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:148:14)
<asynchronous suspension>
#8      main (file:///C:/Users/yaswa/AppData/Local/Pub/Cache/hosted/pub.dev/very_good_cli-0.13.1/bin/very_good.dart:5:24)
<asynchronous suspension>
```

**Expected Behavior**
Should create a federated plugin code.

**Additional Context**
- `very_good_cli` - 0.13.1

```
Edition	Windows 11 Pro Insider Preview
Version	22H2
Installed on	‎20-‎01-‎2023
OS build	25281.1000
Experience	Windows Feature Experience Pack 1000.25281.1000.0
```

**Comment by yahu1031** [comment]
<summary>
Verbose logs
<details>

```console
PS C:\Users\yaswa\Desktop> very_good create flutter_plugin sky_client --verbose
Argument information:
  Top level options:
  - verbose: true
  Command: create
    Command options:
    Command sub command: flutter_plugin
Running with analytics enabled.
Building generator from brick: very_good_flutter_plugin ^0.3.3
Building generator from brick failed: PathNotFoundException: Directory listing failed, path = 'C:\Users\yaswa\AppData\Local\Mason\Cache\hosted\registry.brickhub.dev\very_good_flutter_plugin_0.3.3\__brick__\{{project_name.snakeCase()}}\{{project_name.snakeCase()}}\example\{{#android}}android{{\android}}\app\src\main\kotlin\com\example\{{project_name.snakeCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
Building generator from bundle very_good_flutter_plugin 0.3.3
Unhandled exception:
PathNotFoundException: Directory listing failed, path = 'C:\Users\yaswa\AppData\Local\Mason\Cache\bundled\very_good_flutter_plugin_0.3.3_22878f28a4fe654485c306b2b7c238e94c4ec37c\__brick__\{{project_name.snakeCase()}}\{{#android}}{{project_name.snakeCase()}}_android{{\android}}\android\src\main\kotlin\{{org_name.pathCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      MasonGenerator._fromBrick (package:mason/src/generator.dart:91:14)
#3      MasonGenerator.fromBundle (package:mason/src/generator.dart:70:27)
<asynchronous suspension>
#4      CreateSubCommand.run (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:199:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:211:18)
<asynchronous suspension>
#7      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:148:14)
<asynchronous suspension>
#8      main (file:///C:/Users/yaswa/AppData/Local/Pub/Cache/hosted/pub.dev/very_good_cli-0.13.1/bin/very_good.dart:5:24)
<asynchronous suspension>
FINE: Pub 2.19.6
Argument information:
  Top level options:
  - verbose: true
  Command: create
    Command options:
    Command sub command: flutter_plugin
Running with analytics enabled.
Building generator from brick: very_good_flutter_plugin ^0.3.3
Building generator from brick failed: PathNotFoundException: Directory listing failed, path = 'C:\Users\yaswa\AppData\Local\Mason\Cache\hosted\registry.brickhub.dev\very_good_flutter_plugin_0.3.3\__brick__\{{project_name.snakeCase()}}\{{project_name.snakeCase()}}\example\{{#android}}android{{\android}}\app\src\main\kotlin\com\example\{{project_name.snakeCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
Building generator from bundle very_good_flutter_plugin 0.3.3
Unhandled exception:
PathNotFoundException: Directory listing failed, path = 'C:\Users\yaswa\AppData\Local\Mason\Cache\bundled\very_good_flutter_plugin_0.3.3_22878f28a4fe654485c306b2b7c238e94c4ec37c\__brick__\{{project_name.snakeCase()}}\{{#android}}{{project_name.snakeCase()}}_android{{\android}}\android\src\main\kotlin\{{org_name.pathCase()}}\*' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      MasonGenerator._fromBrick (package:mason/src/generator.dart:91:14)
#3      MasonGenerator.fromBundle (package:mason/src/generator.dart:70:27)
<asynchronous suspension>
#4      CreateSubCommand.run (package:very_good_cli/src/commands/create/commands/create_subcommand.dart:199:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      VeryGoodCommandRunner.runCommand (package:very_good_cli/src/command_runner.dart:211:18)
<asynchronous suspension>
#7      VeryGoodCommandRunner.run (package:very_good_cli/src/command_runner.dart:148:14)
<asynchronous suspension>
#8      main (file:///C:/Users/yaswa/AppData/Local/Pub/Cache/hosted/pub.dev/very_good_cli-0.13.1/bin/very_good.dart:5:24)
<asynchronous suspension>
IO  : Writing 584 characters to text file C:\Users\yaswa\AppData\Local\Pub\Cache\log\pub_log.txt.
MSG : Logs written to C:\Users\yaswa\AppData\Local\Pub\Cache\log\pub_log.txt.
```
</details>
</summary>

**Comment by yahu1031** [comment]
This happens with all the versions.

**Comment by alestiago** [comment]
I @yahu1031 thanks for opening an issue 💙 !

I've been unable to reproduce this issue. In other words, `very_good create flutter_plugin sky_client` succeeds.

Do you mind sharing the output of `flutter doctor -v`?

**Comment by alestiago** [comment]
Thanks @yahu1031 for the quick reply! I look forward to the update.

Regarding your question, the file [here](https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/blob/main/src/my_plugin/my_plugin_android/android/src/main/kotlin/com/example/my_plugin/MyPluginPlugin.kt) is not being generated. There is only a single file under `my_plugin_android/android/src/main/` and that is the `AndroidManifest.xml`. Although this file is not being generated, the `Unhandled exception` is not reached on create.

The brick does have this [file](https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/tree/main/brick/__brick__/%7B%7Bproject_name.snakeCase()%7D%7D/%7B%7B%23android%7D%7D%7B%7Bproject_name.snakeCase()%7D%7D_android%7B%7B/android%7D%7D/android/src/main/kotlin/%7B%7Borg_name.pathCase()%7D%7D) and there is no post hook. This should definitely be looked into 👀 .

**Comment by renancaraujo** [comment]
Possibly related: https://github.com/felangel/mason/issues/676

**Comment by erickzanardo** [comment]
I can confirm that this is reproducible in Windows.

**Comment by yahu1031** [comment]
@alestiago Sorry about not responding so quickly. I'm away from my Windows machine. So can't give you more info. But LMK if anything is needed and I will try providing it somehow.

**Comment by bawantha** [comment]
This is still happening in windows

**Comment by charles0122** [comment]
This is still happening in windows

**Comment by erickzanardo** [comment]
As I mentioned this mason issue: https://github.com/felangel/mason/issues/676#issuecomment-3499339268

This has been happening because Windows can't handle files/folders that have a too long absolute path.

I don't think there is much we can do to avoid this issue since it is a limitation down in the operational system level, we might be able to think on measures that could potentially decrease the chance of the issue happening though, like for example, the hash of the bundle is added to the name of the file in the cache, and is a long value, maybe we could make it shorter (this would need to be handled on the mason site)?

We have expressions on the files/folder names, like `project_name.snakeCase()`, which is also a little bit long, maybe we could create short aliases for them that we set on a pre hook, saving a lot of characters, this is something that we probably could do directly on the very good cli side!
