### ISSUE TITLE
fix: `very_good test` not working with a dart project depending on non-flutter packages

### ISSUE THREAD

**Issue by dmosdallas** [VeryGoodOpenSource/very_good_cli#732]
**Description**
I'm testing out very_good_cli and attempting to use with a cli I'm developing alongside a Flutter application. I'd really like to make use of the recursive package & test management features of the very_good_cli, but it looks like the tool unconditionally runs `flutter test` for tests kicked off by this package.

I am using a package ([dcli](https://pub.dev/packages/dcli)) which transitively imports `dart:cli`, a library that has no flutter implementation. Now, even though this is a dart-only package, a dependency which is not supported in flutter is causing the tooling to break :/

**Steps To Reproduce**

Start with a clean project & make sure `very_good test` works:

```shell
dallas@funfetti:/tmp$ very_good create dart_cli test_application
✓ Generated 24 file(s) (0.2s)
✓ Running "flutter pub get" in ./test_application (0.9s)
✓ Running "dart fix --apply" in ./test_application (2.0s)


Created a Very Good Dart CLI application! 🦄


$ cd test_application/
$ very_good test
Running "flutter test" in /tmp/test_application...
✓ Optimizing tests (0.1s)
Running: `git rev-parse --show-toplevel` in `/tmp/test_application`
/tmp/test_application
Running: `git diff --relative` in `/tmp/test_application`
Running: `/home/dallas/flutter/bin/cache/dart-sdk/bin/dart run build_runner build --delete-conflicting-outputs` in `/tmp/test_application`
[INFO] Generating build script...
[INFO] Generating build script completed, took 149ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 21ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 237ms

[INFO] Running build...
[INFO] Running build completed, took 4ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 10ms

[INFO] Succeeded after 18ms with 0 outputs (0 actions)

Running: `git diff --relative` in `/tmp/test_application`
00:01 +19: All tests passed!
```

Now import a package without a flutter implementation:
```shell
$ dart pub add dcli
Resolving dependencies...
+ ...
Changed 32 dependencies!
```

Update one of the tests to use the package, here is `ensure_build_test.dart` with that package being used:
```dart
@Tags(['version-verify'])
library ensure_build_test;

import 'package:build_verify/build_verify.dart';
import 'package:dcli/dcli.dart';  // <-- import the new package
import 'package:test/test.dart';

void main() {
  env.HOME;  // <-- NOP that uses the library
  test('ensure_build', expectBuildClean);
}

```

And now run the tests again:
```shell
$ very_good test
Running "flutter test" in /tmp/test_application...
✓ Optimizing tests (97ms)
/home/dallas/.pub-cache/hosted/pub.dev/dcli-2.1.0/lib/src/util/wait_for_ex.dart:10:8: Error: Dart library 'dart:cli' is not available on this platform.
import 'dart:cli' as cli;
       ^
Context: The unavailable library 'dart:cli' is imported through these packages:

../../test_application/test/ensure_build_test.dart => package:dcli => dart:cli

Detailed import paths for (some of) the these imports:

    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/functions/copy.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli
    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/functions/echo.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli
    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/functions/move.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli
    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/functions/move_dir.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli
    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/functions/touch.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli
    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/util/file_util.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli
    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/util/temp_file.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli
    listener.dart => ../../test_application/test/.test_optimizer.dart => ../../test_application/test/ensure_build_test.dart => package:dcli/dcli.dart => package:dcli/src/util/wait_for_ex.dart => dart:cli

/home/dallas/.pub-cache/hosted/pub.dev/dcli-2.1.0/lib/src/util/wait_for_ex.dart:38:17: Error: Method not found: 'waitFor'.
    value = cli.waitFor<T>(wrapped);
                ^^^^^^^

Failed to load "/tmp/test_application/test/.test_optimizer.dart": Compilation failed for testPath=/tmp/test_application/test/.test_optimizer.dart
Unhandled exception:
Null check operator used on a null value
#0      _actualTestPath (package:very_good_cli/src/cli/flutter_cli.dart:502:62)
#1      _flutterTest.<anonymous closure> (package:very_good_cli/src/cli/flutter_cli.dart:398:13)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#4      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#5      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#6      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

**Expected Behavior**
Tests that succeed when running `dart test` should also work when running `very_good test`

**Screenshots**

**Additional Context**

**Comment by renancaraujo** [comment]
Related: https://github.com/VeryGoodOpenSource/very_good_cli/issues/505
