### ISSUE TITLE
`Error: Zone mismatch` when adding `ensureInitialized()` inside main in flutter 3.10.0 stable

### ISSUE THREAD

**Issue by mariopepe** [VeryGoodOpenSource/very_good_cli#734]
**Description**
`Error: Zone mismatch` when adding `ensureInitialized()` inside main. Only in stable 3.10.0

The full error text is:

```console
Zone mismatch.
The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).
      #0      BindingBase.debugCheckZone.<anonymous closure> (package:flutter/src/foundation/binding.dart:497:29)
      #1      BindingBase.debugCheckZone (package:flutter/src/foundation/binding.dart:502:6)
      #2      runApp (package:flutter/src/widgets/binding.dart:1080:18)
      #3      bootstrap.<anonymous closure> (package:my_app/bootstrap.dart:31:17)
      <asynchronous suspension>
      #4      bootstrap (package:my_app/bootstrap.dart:30:3)
      <asynchronous suspension>
      #5      main (package:my_app/main_development.dart:8:3)
      <asynchronous suspension>
```

**Steps To Reproduce**

1. Create a new project with the cli `very_good create flutter_app my_app`
2. Edit the `main_development.dart` file adding `WidgetsFlutterBinding.ensureInitialized();` So that it looks like:

```dart
import 'package:flutter/material.dart';
import 'package:my_app/app/app.dart';
import 'package:my_app/bootstrap.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await bootstrap(() => const App());
}
```

3. Run the project and you will get the above mentioned error

**Expected Behavior**
No error

**Additional Context**
It was not happening on flutter 3.7.x, it only happens in 3.10.0

**Comment by orestesgaolin** [comment]
Having the same issue, got really surprised and initially thought it's a false positive, but it seems that default template is introducing new zone in `bootstrap` to capture errors. When creating dependencies I initialize them before calling `bootstrap`, so calling `WidgetsFlutterBinding.ensureInitialized();` is sometimes necessary outside of the inner zone. 

One approach would be to not introduce new zone inside `bootstrap`, the other is to move initialization logic into the zone.

**Comment by yuruyuri16** [comment]
After reading this: **calls to WidgetsFlutterBinding.ensureInitialized() should be run in the same zone as calls to runApp()**. I modified my code like this.

```dart
Future<void> bootstrap(AppBuilder builder) async {
  FlutterError.onError = (details) {
    log(details.exceptionAsString(), stackTrace: details.stack);
  };

  Bloc.observer = const AppBlocObserver();

  await runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      final sharedPreferences = await SharedPreferences.getInstance();
      runApp(
        await builder(
          sharedPreferences,
        ),
      );
    },
    (error, stackTrace) => log(error.toString(), stackTrace: stackTrace),
  );
}
```
I am not sure is this is right way to do it but the error message is gone.

**Comment by renancaraujo** [comment]
We are removing that zone creation from all templates. Although, I suggest adding cross-flavor setup code inside the bootstrap function (that is what it is for).

**Comment by renancaraujo** [comment]
This was fixed by https://github.com/VeryGoodOpenSource/very_good_core/pull/270/files which will be introduced ion #744

**Comment by renancaraujo** [comment]
Yeah, just released 0.15.0. This should be fixed.

**Comment by ariefsn** [comment]
For me, I update the `bootstrap.dart`
```dart
Future<void> bootstrap(
  FutureOr<Widget> Function() builder, {
  Future<void> Function()? onStart,
}) async {
  FlutterError.onError = (details) {
    log(details.exceptionAsString(), stackTrace: details.stack);
  };

  Bloc.observer = AppBlocObserver();

  await runZonedGuarded(
    () async {
      await onStart?.call();
      return runApp(await builder());
    },
    (error, stackTrace) => log(error.toString(), stackTrace: stackTrace),
  );
}
```

and pass to the `onStart` param
